### ISSUE TITLE
question :Does it support scope setting ACL

### ISSUE THREAD

**Issue by pigochu** [foxford/mqtt-gateway#78]
RabbitMQ's approach is as follows

```json
{
   "aud": "xxxx",
    "iat": 123000,
    "exp": 123123,
    "scopes": ["read:/xxx" , "write:/xxx"]
}
```

Does this plugin have similar practices?

https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2

**Comment by khodzha** [comment]
No, there are no scopes passed with tokens.
The topics list client is allowed to subscribe to is based on `connection_mode` user property and some hardcoded conventions.

Conventions are basically like this:
- User clients (i.e. clients with no connection_mode set) are allowed to subscribe to `/agents/#{client_id}/some/app/topic/{input, output}`
- `connection_mode=service` clients are allowed to subscribe to something like `/agents/+/this/app/topic/{input, output}` (ie to topics of this app under each agent)
